version: "2"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    command: "--logpath=/dev/null"
